project:
  type: website
  resources:
    -Kali_Olmsted_Resume.pdf


website:
  reader-mode: true
  navbar:
    title: false
    background: white
    foreground: "gray-800"
    collapse-below: sm  
    left:
      - href: index.qmd
        text: About
      - href: my_projects.qmd
        text: My Projects
  page-footer:
    right: "&copy; 2025, Kali Olmsted"
    
